### ISSUE TITLE
Fixing the case of the nagging apostrophe which follows the word-ending letter s

### ISSUE THREAD

**Issue by amirsol81** [ultrasound1372/NVDA-IBMTTS-Driver#20]
As you might have noticed, if a word ending in the letter s is followed by an apostrophe, Eloquence erroneously thinks that word needs to be treated and read as a possessive. As a case in point, please check this:
Epic Games, Spotify, and Tile Form 'Coalition for App Fairness' to 'Fight Back' Against Apple
This erroneous possessive is announced both in continuous reading and in word-by-word navigation. So would it be possible, one way or another, to fix it via IBMTTS?

**Comment by ultrasound1372** [comment]
Unfortunately no. This is used to indicate in English when possession is by the plural. The nonstandard practice is using apostrophies as quotation markers, as far as I'm aware. Unless that is a standard practice for embedded quotes inside other quotes.

**Comment by amirsol81** [comment]
I know, but unlike many other engines Eloquence mishandles it.
