### ISSUE TITLE
Anticrash expressions generating serious pronunciation issues

### ISSUE THREAD

**Issue by amirsol81** [ultrasound1372/NVDA-IBMTTS-Driver#25]
Using the latest release of IBMTTS driver I noticed that certain word combinations are mispronounced. Interestingly, the same issue can't be duplicated with Eloquence SAPI 4 which doesn't have antichrash expressions. Some of the mispronounced words are:
dorchester
orchestra
orchestral
orchestrally
orchestrate
orchestration
orchestrator
orchestrina
orchestrion
chichester
colchester
manchester
rochester
winchester
caesura
caesurae
caesural
caesuric
@ultrasound1372 Would you please take a look?

**Comment by Mohamed00** [comment]
The hes glitches should be fixed when my PR is merged. the cae issues 
are happening because of the anticrash expression. There are over 300 
ways to crash it with that one string, so it was decided early on to 
just block it entirely, though that crash could probably be completely 
fixed with a root entry. I think the synth wants to say `[k1iZR] or 
`[k1eZR].

**Comment by amirsol81** [comment]
@Mohamed00 Thanks for the explanation. The "hes" glitch is much more prominent IMO given the number of words it affects.

**Comment by ultrasound1372** [comment]
@amirsol81 your hes words should be fixed now that that PR is merged. I'm unsure as to how the cae words are suppose to be pronounced.

**Comment by amirsol81** [comment]
@ultrasound1372 Should I need to replace ibmeci.py, updated today, to get the fix? I'm asking this because I just replaced it, but the "hes" glitch is still there, affecting all words like, say, orchestra.
As for the "caes" stuff, these are the pronunciations:
caesura	`[.0sX.1zyur.0x]
caesurae	`[.0sX.1zyur.0i]
caesuric	`[.0sX.1zyu.0rXk]
caesural	`[.0sX.1zyu.0rxl]

**Comment by amirsol81** [comment]
@Mohamed00 Does the latest fix correct words like "Manchester" for you? I still have pronunciation issues with such words.

**Comment by ultrasound1372** [comment]
I don't, strange. I pulled the latest from personal, it changes ibmeci.py, and built.

**Comment by Mohamed00** [comment]
Yes, it does seem to.

**Comment by amirsol81** [comment]
@Mohamed00 @ultrasound1372 Strange! Mine persists. So could either of you kindly send me your copy of ibmeci.py which fixes the issue? My email address, whose spaces should be removed, is m o b i l e s p a c e 0 8 @gmail.com. Also any chance of sending me your copy of Eloquence pronunciation correction facility which isn't SAPI 4-based?
