### ISSUE TITLE
48cf38

### ISSUE THREAD

**Issue by dan1982code** [ultrasound1372/NVDA-IBMTTS-Driver#26]
Hi, some hex strings like 48cf38 have the word 'compare' (for cf) spoken. Is there a way to fix this? Thank you for this fork!

**Comment by Mohamed00** [comment]
Uncheck the Enable abbreviation dictionary checkbox.

**Comment by ultrasound1372** [comment]
That actually isn't the problem. We are however unable to mitigate this without mangling the pronunciation of strings in other ways.
