### ISSUE TITLE
Words containing "iot" are mispronounced

### ISSUE THREAD

**Issue by amirsol81** [ultrasound1372/NVDA-IBMTTS-Driver#29]
The latest changes to the driver, and even the one before it, have broken words containing "iot". Now words like "idiot" and "Elliott" are mispronounced. Can anyone confirm?

**Comment by amirsol81** [comment]
@ultrasound1372 Would you please take a look at this?

**Comment by ultrasound1372** [comment]
I have no idea where this comes from, possibly something in the community dictionary you're using? Have you tried removing the dictionaries and trying again? I am not getting these problems here, though I'm out of date on my community dictionary, and am not using the driver which has unmerged pull requests.

**Comment by amirsol81** [comment]
@ultrasound1372 I just noticed that it's an NVDA dictionary item which was causing it. I had created an NVDA dictionary item for "IoT", and now it's removed.
