### ISSUE TITLE
New NVDA alphas break IBMTTS compatibility

### ISSUE THREAD

**Issue by amirsol81** [ultrasound1372/NVDA-IBMTTS-Driver#37]
I just tried installing NVDA Alpha 21895, but as the installation screen appeared, IBMTTS stopped talking. The TTS no longer appears in the list of available speech engines. So it seems to me that either this or one of the most recent alphas has broken IBMTTS compatibility. It might be because of Python 3.8 support on the side of NVDA though I'm not sure.

**Comment by Mohamed00** [comment]
It's due to a removal of something in the latest alphas that the driver 
relied on. I'll get a fix out at some point soon but in the meantime, 
use an earlier alpha like 21877 or below, or NVDA 2020.4.

**Comment by amirsol81** [comment]
@Mohamed00 Thanks. Looking forward to the fix.
