### ISSUE TITLE
Any chance of upsampling the Eloquence TTS audio output?

### ISSUE THREAD

**Issue by amirsol81** [ultrasound1372/NVDA-IBMTTS-Driver#9]
This is more of a suggestion rather than an issue.
If I'm not mistaken, IBMTTS uses 22000 HZ for its output. However, I'm wondering if we can upsample the output to something like 44100. Not sure if it can improve our listening experience, but it would be a good idea to give the higher sample a try. So any chance of doing it as a user-configurable option from NVDA's Synthesizer dialog?

**Comment by amirsol81** [comment]
As a follow-up, Eloquence for Android has such an option and I think Nuance TALKS&Zooms used to have it. I'm not sure if their highest audio sample rate is higher than what we currently have, though.

**Comment by Mohamed00** [comment]
Probably not. Eloquence has always ran at 11 kHz, and the upsampling is 
probably coming from SAPI, not the synth itself. Eloquence for Android 
has a 16 kHz option, but that never made it to the desktop or even 
Windows Mobile, you can only get it in Android or in Eloquence for 
Symbian. I'm pretty sure upsampling would probably not do much except 
cause weird interpolation artifacts, anyway.

**Comment by amirsol81** [comment]
Ah, I see. Just thought it could be achieved like some of the features 
made possible by this new development branch. Thanks.

**Comment by ultrasound1372** [comment]
Nah, upsampling properly would add no more than there already is. And upsampling poorly, like SAPI does, would make it sound like ass, with zero-order holds causing extra highs to appear where there were none. Besides, I am not upsampling anything in pure python in real-time.
